/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    informes: Informe;
    cardapio: Cardapio;
    cronologia: Cronologia;
    pedidos: Pedido;
    caixa: Caixa;
    'produtos-pimenta': ProdutosPimenta;
    'pedidos-pimenta': PedidosPimenta;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    informes: InformesSelect<false> | InformesSelect<true>;
    cardapio: CardapioSelect<false> | CardapioSelect<true>;
    cronologia: CronologiaSelect<false> | CronologiaSelect<true>;
    pedidos: PedidosSelect<false> | PedidosSelect<true>;
    caixa: CaixaSelect<false> | CaixaSelect<true>;
    'produtos-pimenta': ProdutosPimentaSelect<false> | ProdutosPimentaSelect<true>;
    'pedidos-pimenta': PedidosPimentaSelect<false> | PedidosPimentaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('pt' | 'en') | ('pt' | 'en')[];
  globals: {
    configuracoes: Configuracoe;
  };
  globalsSelect: {
    configuracoes: ConfiguracoesSelect<false> | ConfiguracoesSelect<true>;
  };
  locale: 'pt' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Obrigatório para clientes (validado em hook).
   */
  nome?: string | null;
  /**
   * Obrigatório para clientes (validado em hook).
   */
  sobrenome?: string | null;
  /**
   * Obrigatório para clientes: é o vínculo com os pedidos de delivery (gravado só com dígitos).
   */
  telefone?: string | null;
  /**
   * Localização opcional do cliente (ponto no mapa), usada nos pedidos.
   */
  latitude?: number | null;
  longitude?: number | null;
  /**
   * Referência textual opcional (no Vale do Capão não há endereço formal).
   */
  localidade?: string | null;
  role: 'admin' | 'funcionario' | 'cliente';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "informes".
 */
export interface Informe {
  id: number;
  titulo: string;
  /**
   * Gerado automaticamente a partir do título se deixado em branco.
   */
  slug?: string | null;
  data?: string | null;
  etiqueta: 'Funcionamento' | 'Reflorestamento' | 'Horta' | 'Compostagem' | 'Apiário' | 'Viveiro' | 'Cardápio';
  resumo?: string | null;
  corpo?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Imagem de capa em proporção 1:1.
   */
  capa?: (number | null) | Media;
  /**
   * No máximo um informe pode estar em destaque por vez.
   */
  destaque?: boolean | null;
  publicado?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cardapio".
 */
export interface Cardapio {
  id: number;
  secao: 'Pizzas' | 'Tamanhos' | 'Bebidas' | 'Vinhos';
  nome: string;
  detalhe?: string | null;
  /**
   * Valor numérico em reais (ex.: 30 para "R$ 30,00"). Deixe vazio em itens cujo preço depende do tamanho (pizzas).
   */
  preco?: number | null;
  ordem?: number | null;
  ativo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cronologia".
 */
export interface Cronologia {
  id: number;
  /**
   * Texto livre (ex.: "1992", "hoje", "ano a confirmar"). Nunca reformatado como número.
   */
  ano?: string | null;
  titulo: string;
  texto?: string | null;
  ilustracao?: (number | null) | Media;
  ordem?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pedidos".
 */
export interface Pedido {
  id: number;
  /**
   * Código público gerado automaticamente na criação. O cliente o usa como referência na conversa do WhatsApp.
   */
  codigo?: string | null;
  nome: string;
  telefone: string;
  itens: {
    item: number | Cardapio;
    quantidade: number;
    /**
     * Obrigatório quando o item é uma pizza (sem preço próprio): o preço vem do item da seção Tamanhos.
     */
    tamanho?: (number | null) | Cardapio;
    /**
     * Nome do item no momento do pedido, preenchido no servidor.
     */
    nomeSnapshot?: string | null;
    /**
     * Preço unitário resolvido no servidor a partir do cardápio (item ou tamanho) no momento do pedido.
     */
    precoUnitario?: number | null;
    id?: string | null;
  }[];
  latitude: number;
  longitude: number;
  /**
   * Indicação textual opcional de localidade ou ponto de referência (no Vale do Capão não há endereço formal).
   */
  localidade?: string | null;
  observacoes?: string | null;
  /**
   * Soma dos produtos calculada no servidor a partir dos preços atuais do cardápio. NÃO inclui frete — o preço final é informado ao cliente pelo atendente via mensagem.
   */
  subtotal?: number | null;
  /**
   * Visível ao cliente no dashboard /area-cliente (RN09 revogada): pendente → "Recebido", pago → "Pagamento confirmado", em_transito → "Saiu para entrega", finalizado → "Entregue". Atualize conforme a conversa no WhatsApp avança.
   */
  status: 'pendente' | 'pago' | 'em_transito' | 'finalizado';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "caixa".
 */
export interface Caixa {
  id: number;
  /**
   * Gerado automaticamente na criação.
   */
  codigo?: string | null;
  mesa?: string | null;
  itens: {
    item: number | Cardapio;
    quantidade: number;
    tamanho?: (number | null) | Cardapio;
    nomeSnapshot?: string | null;
    precoUnitario?: number | null;
    id?: string | null;
  }[];
  subtotal?: number | null;
  servico?: boolean | null;
  taxaServico?: number | null;
  desconto?: number | null;
  total?: number | null;
  pagamentos?:
    | {
        valor: number;
        forma?: ('pix' | 'dinheiro' | 'cartao') | null;
        pago?: boolean | null;
        pagoEm?: string | null;
        editado?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Derivado: "Paga" quando todas as partes estão pagas.
   */
  status: 'aberta' | 'paga';
  funcionario?: (number | null) | User;
  observacoes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "produtos-pimenta".
 */
export interface ProdutosPimenta {
  id: number;
  nome: string;
  /**
   * Ex.: "150 ml", "1 L".
   */
  volume?: string | null;
  descricao?: string | null;
  preco: number;
  /**
   * Opcional. Aplicado a cada unidade quando a quantidade pedida atinge o lote mínimo.
   */
  precoLote?: number | null;
  /**
   * Quantidade a partir da qual vale o preço de lote. Obrigatório se houver preço de lote.
   */
  loteMinimo?: number | null;
  imagem?: (number | null) | Media;
  ordem?: number | null;
  ativo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pedidos-pimenta".
 */
export interface PedidosPimenta {
  id: number;
  /**
   * Código público gerado na criação — referência na conversa do WhatsApp.
   */
  codigo?: string | null;
  nome: string;
  telefone: string;
  /**
   * Opcional: restaurante ou comércio que fez o pedido.
   */
  estabelecimento?: string | null;
  itens: {
    produto: number | ProdutosPimenta;
    quantidade: number;
    nomeSnapshot?: string | null;
    precoUnitario?: number | null;
    lote?: boolean | null;
    id?: string | null;
  }[];
  modalidade: 'entrega' | 'retirada';
  latitude?: number | null;
  longitude?: number | null;
  localidade?: string | null;
  observacoes?: string | null;
  /**
   * Calculado no servidor (preço unitário ou de lote). Não inclui frete — combinado pelo WhatsApp.
   */
  subtotal?: number | null;
  /**
   * Mesmo funil do delivery. Na retirada, "Em trânsito" aparece ao cliente como "Pronto para retirada".
   */
  status: 'pendente' | 'pago' | 'em_transito' | 'finalizado';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'informes';
        value: number | Informe;
      } | null)
    | ({
        relationTo: 'cardapio';
        value: number | Cardapio;
      } | null)
    | ({
        relationTo: 'cronologia';
        value: number | Cronologia;
      } | null)
    | ({
        relationTo: 'pedidos';
        value: number | Pedido;
      } | null)
    | ({
        relationTo: 'caixa';
        value: number | Caixa;
      } | null)
    | ({
        relationTo: 'produtos-pimenta';
        value: number | ProdutosPimenta;
      } | null)
    | ({
        relationTo: 'pedidos-pimenta';
        value: number | PedidosPimenta;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  nome?: T;
  sobrenome?: T;
  telefone?: T;
  latitude?: T;
  longitude?: T;
  localidade?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "informes_select".
 */
export interface InformesSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  data?: T;
  etiqueta?: T;
  resumo?: T;
  corpo?: T;
  capa?: T;
  destaque?: T;
  publicado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cardapio_select".
 */
export interface CardapioSelect<T extends boolean = true> {
  secao?: T;
  nome?: T;
  detalhe?: T;
  preco?: T;
  ordem?: T;
  ativo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cronologia_select".
 */
export interface CronologiaSelect<T extends boolean = true> {
  ano?: T;
  titulo?: T;
  texto?: T;
  ilustracao?: T;
  ordem?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pedidos_select".
 */
export interface PedidosSelect<T extends boolean = true> {
  codigo?: T;
  nome?: T;
  telefone?: T;
  itens?:
    | T
    | {
        item?: T;
        quantidade?: T;
        tamanho?: T;
        nomeSnapshot?: T;
        precoUnitario?: T;
        id?: T;
      };
  latitude?: T;
  longitude?: T;
  localidade?: T;
  observacoes?: T;
  subtotal?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "caixa_select".
 */
export interface CaixaSelect<T extends boolean = true> {
  codigo?: T;
  mesa?: T;
  itens?:
    | T
    | {
        item?: T;
        quantidade?: T;
        tamanho?: T;
        nomeSnapshot?: T;
        precoUnitario?: T;
        id?: T;
      };
  subtotal?: T;
  servico?: T;
  taxaServico?: T;
  desconto?: T;
  total?: T;
  pagamentos?:
    | T
    | {
        valor?: T;
        forma?: T;
        pago?: T;
        pagoEm?: T;
        editado?: T;
        id?: T;
      };
  status?: T;
  funcionario?: T;
  observacoes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "produtos-pimenta_select".
 */
export interface ProdutosPimentaSelect<T extends boolean = true> {
  nome?: T;
  volume?: T;
  descricao?: T;
  preco?: T;
  precoLote?: T;
  loteMinimo?: T;
  imagem?: T;
  ordem?: T;
  ativo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pedidos-pimenta_select".
 */
export interface PedidosPimentaSelect<T extends boolean = true> {
  codigo?: T;
  nome?: T;
  telefone?: T;
  estabelecimento?: T;
  itens?:
    | T
    | {
        produto?: T;
        quantidade?: T;
        nomeSnapshot?: T;
        precoUnitario?: T;
        lote?: T;
        id?: T;
      };
  modalidade?: T;
  latitude?: T;
  longitude?: T;
  localidade?: T;
  observacoes?: T;
  subtotal?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuracoes".
 */
export interface Configuracoe {
  id: number;
  endereco?: string | null;
  /**
   * URL do Google Maps ou similar.
   */
  linkMapa?: string | null;
  horarios?:
    | {
        faixa?: string | null;
        horario?: string | null;
        id?: string | null;
      }[]
    | null;
  whatsapp?: string | null;
  instagram?: string | null;
  email?: string | null;
  chavePix?: string | null;
  qrPix?: (number | null) | Media;
  taxasEntrega?:
    | {
        distancia?: string | null;
        valor?: string | null;
        id?: string | null;
      }[]
    | null;
  avisoRetirada?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuracoes_select".
 */
export interface ConfiguracoesSelect<T extends boolean = true> {
  endereco?: T;
  linkMapa?: T;
  horarios?:
    | T
    | {
        faixa?: T;
        horario?: T;
        id?: T;
      };
  whatsapp?: T;
  instagram?: T;
  email?: T;
  chavePix?: T;
  qrPix?: T;
  taxasEntrega?:
    | T
    | {
        distancia?: T;
        valor?: T;
        id?: T;
      };
  avisoRetirada?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}